### ISSUE TITLE
Binder launch button not working 

### ISSUE THREAD

**Issue by arnim** [eurostat/PRost#2]
Warning messages:
1: In install.packages("devtools", , repos = "https://cloud.r-project.org") :
  installation of package ‘usethis’ had non-zero exit status
2: In install.packages("devtools", , repos = "https://cloud.r-project.org") :
  installation of package ‘devtools’ had non-zero exit status
Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
Removing intermediate container 00e021666daf
The command '/bin/sh -c echo "install.packages('glue',repos='https://cloud.r-project.org');"  > /tmp/install.R &&     echo "update.packages" >> /tmp/install.R &&     echo "install.packages('devtools',,repos='https://cloud.r-project.org');"  > /tmp/install.R &&     echo "devtools::install_github('IRkernel/IRkernel');" >> /tmp/install.R &&     echo "install.packages(c('rJava','rdbnomics','ggrepel','ggraph','ggiraph','ggnetwork','ggTimeSeries','plotrix','tmap','rsdmx','leaflet','shinyjs','TSsdmx','TSdbi','timeSeries','RJDemetra'),repos='https://cloud.r-project.org')" >> /tmp/install.R &&     echo "devtools::install_github('eurostat/flagr');" >> /tmp/install.R &&     echo "devtools::install_github('eurostat/restatapi');" >> /tmp/install.R &&     echo "devtools::install_github('rOpenGov/eurostat');" >> /tmp/install.R &&     Rscript /tmp/install.R' returned a non-zerocode: 1

**Comment by mmatyi** [comment]
The Dockerfile was rebuilt and now the launch binder button  is working.
