### ISSUE TITLE
eurostat_package_tutorial.ipynb: Error in get_eurostat_raw(id): ten00081 does not exist or is not readable

### ISSUE THREAD

**Issue by arnim** [eurostat/PRost#3]
Error in get_eurostat_raw(id): ten00081 does not exist or is not readable. Some datasets are not accessible via the eurostat interface. You can try to search the data manually from the comext database at http://epp.eurostat.ec.europa.eu/newxtweb/ or bulk download facility at http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing or annual Excel files http://ec.europa.eu/eurostat/web/prodcom/data/excel-files-nace-rev.2
Traceback:

1. get_eurostat("ten00081") %>% label_eurostat(dat) %>% filter(time == 
 .     "2013-01-01", product != "Renewable energies") %>% mutate(nproduct = dict[as.character(product)], 
 .     geo = gsub(geo, pattern = " \\(.*", replacement = "")) %>% 
 .     select(nproduct, geo, values) %>% group_by(nproduct, geo) %>% 
 .     summarise(svalue = sum(values)) %>% group_by(geo) %>% mutate(tvalue = sum(svalue), 
 .     svalue = svalue/sum(svalue)) %>% filter(tvalue > 1000) %>% 
 .     spread(nproduct, svalue)
2. eval(lhs, parent, parent)
3. eval(lhs, parent, parent)
4. get_eurostat("ten00081")
5. get_eurostat_raw(id)
6. stop(id, " does not exist or is not readable", msg)

In [15]
http://mybinder.org/v2/gh/eurostat/PRost/master?urlpath=notebooks%2Feurostat_package_tutorial.ipynb

**Comment by mmatyi** [comment]
The notebook was modified following the update of the tutorial [online version](http://ropengov.github.io/eurostat/articles/eurostat_tutorial.html). The results in the notebook and in the online tutorial is not always the same, as the online tutorial still uses the old output/results as in the pdf version.  Where the code from the online tutorial still provided error, the dataset were changed.
